# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up environment
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/setup_env.sh
          $GITHUB_WORKSPACE/ci/setup_env.sh

      - name: Runing tests
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/test.sh
          $GITHUB_WORKSPACE/ci/test.sh

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setting up environment
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/setup_env.sh
          $GITHUB_WORKSPACE/ci/setup_env.sh

      - name: Building adn deploying application
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/deploy.sh
          $GITHUB_WORKSPACE/ci/deploy.sh