# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up environment
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/setup_env.sh
          $GITHUB_WORKSPACE/ci/setup_env.sh

      - name: Runing tests
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/test.sh
          $GITHUB_WORKSPACE/ci/test.sh

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up environment
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/setup_env.sh
          $GITHUB_WORKSPACE/ci/setup_env.sh

      - name: Building application
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/build.sh
          $GITHUB_WORKSPACE/ci/build.sh

      - name: Deploying application
        run: |
          chmod +x $GITHUB_WORKSPACE/ci/deploy.sh
          $GITHUB_WORKSPACE/ci/deploy.sh